<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Aspire">
    <PackageVersion Include="Aspire.Hosting.SqlServer" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.Testing" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup Label="Assertions">
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup Label="EntityFrameworkCore">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup Label="Testing Frameworks">
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.0" />
  </ItemGroup>
</Project>
