<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <UserSecretsId>aspire-day25-apphost</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
        <PackageReference Include="Aspire.Hosting.Redis"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\Day25.Api\Day25.Api.csproj"/>
    </ItemGroup>
</Project>
