using AwesomeAssertions.Equivalency;
using AwesomeAssertions.Primitives;

namespace Day05.Tests.Extensions;

// 為電商專案建立的自訂Assertions
public static class ECommerceAssertions
{
    public static AndConstraint<ObjectAssertions> BeValidProduct(this ObjectAssertions assertions)
    {
        var product = assertions.Subject as Product;

        product.Should().NotBeNull("預期為 Product 物件，但找到 {0}", assertions.Subject?.GetType());
        product!.Id.Should().BeGreaterThan(0, "預期 Product.Id 大於 0，但找到 {0}", product.Id);
        product.Name.Should().NotBeNullOrEmpty("預期 Product.Name 不為 null 或空值");
        product.Price.Should().BeGreaterThan(0, "預期 Product.Price 大於 0，但找到 {0}", product.Price);

        return new AndConstraint<ObjectAssertions>(assertions);
    }

    public static AndConstraint<ObjectAssertions> BeValidOrder(this ObjectAssertions assertions)
    {
        var order = assertions.Subject as Order;

        order.Should().NotBeNull("預期為 Order 物件");
        order!.Items.Should().NotBeNullOrEmpty("預期 Order 至少包含一個項目");
        order.TotalAmount.Should().BeGreaterThan(0, "預期 Order.TotalAmount 大於 0");

        return new AndConstraint<ObjectAssertions>(assertions);
    }

    public static void ShouldBeValidUser(this User user)
    {
        user.Should().NotBeNull();
        user.Id.Should().BeGreaterThan(0);
        user.Email.Should().NotBeNullOrEmpty();
    }

    public static void ShouldBeComplete(this UserProfile? profile)
    {
        profile.Should().NotBeNull();
        profile!.FirstName.Should().NotBeNullOrEmpty();
        profile.LastName.Should().NotBeNullOrEmpty();
    }
}

public static class ConditionalAssertions
{
    public static ConditionalAssertion<T> When<T>(this T subject, bool condition)
    {
        return new ConditionalAssertion<T>(subject, condition);
    }
}

public class ConditionalAssertion<T>
{
    private readonly T _subject;
    private readonly bool _condition;

    public ConditionalAssertion(T subject, bool condition)
    {
        this._subject = subject;
        this._condition = condition;
    }

    public AndConstraint<ObjectAssertions> Then(Action<T> assertion)
    {
        if (this._condition)
        {
            assertion(this._subject);
        }

        return new AndConstraint<ObjectAssertions>(this._subject.Should());
    }

    public ConditionalAssertion<T> And => this;
}

public static class SmartExclusionExtensions
{
    public static EquivalencyOptions<T> ExcludingAutoGeneratedFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options.Excluding(ctx => ctx.Path.EndsWith("At"))
                      .Excluding(ctx => ctx.Path.EndsWith("Time"))
                      .Excluding(ctx => ctx.Path.Contains("Version"))
                      .Excluding(ctx => ctx.Path.Contains("RowVersion"))
                      .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    public static EquivalencyOptions<T> ExcludingAuditFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options.Excluding(ctx => ctx.Path.Contains("CreatedBy"))
                      .Excluding(ctx => ctx.Path.Contains("CreatedAt"))
                      .Excluding(ctx => ctx.Path.Contains("ModifiedBy"))
                      .Excluding(ctx => ctx.Path.Contains("ModifiedAt"))
                      .Excluding(ctx => ctx.Path.Contains("LastModified"));
    }
}
